### ISSUE TITLE
Can't create_autospec with name argument

### ISSUE THREAD

**Issue by GoogleCodeExporter** [testing-cabal/mock#224]
```
What steps will reproduce the problem?

Run the following code:

import mock
def a():
 print "blah"
q = mock.create_autospec(a, name="a")

What is the expected output? What do you see instead?

I expected the creation of an autospec'd mock with the name "a". Instead, the 
following exception is raised:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/mock.py", line 2186, in create_autospec
    name=_name, **_kwargs)
TypeError: type object got multiple values for keyword argument 'name'

What version of the product are you using? On what operating system?

Mock 1.0.1 on arch linux.

Please provide any additional information below.

Creating a mock with a name attribute works fine.
```

Original issue reported on code.google.com by `plasmash...@gmail.com` on 8 Apr 2014 at 12:14

**Comment by rbtcollins** [comment]
Works for me in 1.3.
