### ISSUE TITLE
Cannot autospec mock builtins.print in python3.4

### ISSUE THREAD

**Issue by GoogleCodeExporter** [testing-cabal/mock#234]
```
This code works prior to 3.4:

```
import builtins
import mock

with mock.patch.object(builtins, 'print', autospec=True):
    print('hai')
```

In 3.4:

```
$ python test.py 
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    with mock.patch.object(builtins, 'print', autospec=True):
  File "/tmp/venv34/lib/python3.4/site-packages/mock.py", line 1349, in __enter__
    _name=self.attribute, **kwargs)
  File "/tmp/venv34/lib/python3.4/site-packages/mock.py", line 2193, in create_autospec
    _check_signature(spec, mock, is_type, instance)
  File "/tmp/venv34/lib/python3.4/site-packages/mock.py", line 213, in _check_signature
    _copy_func_details(func, checksig)
  File "/tmp/venv34/lib/python3.4/site-packages/mock.py", line 221, in _copy_func_details
    funcopy.__module__ = func.__module__
AttributeError: 'method-wrapper' object has no attribute '__module__'
```
```

Original issue reported on code.google.com by `asott...@yelp.com` on 7 Jul 2014 at 11:23

**Comment by rbtcollins** [comment]
3.4 was incompatible with mock, but now fixed.
