### ISSUE TITLE
Incompatible dictionary comprehension with Python 2.6 and Mock 1.1.1.

### ISSUE THREAD

**Issue by KelSolaar** [testing-cabal/mock#260]
The latest Mock version is not working with Python 2.6 anymore: https://travis-ci.org/colour-science/colour/jobs/70356189#L566

```python
ERROR: Failure: SyntaxError (invalid syntax (mock.py, line 132))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/colour-test/lib/python2.6/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/miniconda/envs/colour-test/lib/python2.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/miniconda/envs/colour-test/lib/python2.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/build/colour-science/colour/colour/appearance/tests/tests_llab.py", line 16, in <module>
    import mock
  File "/home/travis/miniconda/envs/colour-test/lib/python2.6/site-packages/mock/__init__.py", line 2, in <module>
    import mock.mock as _mock
  File "/home/travis/miniconda/envs/colour-test/lib/python2.6/site-packages/mock/mock.py", line 132
    _builtins = {name for name in dir(builtins) if not name.startswith('_')}
                        ^
SyntaxError: invalid syntax
```

**Comment by rbtcollins** [comment]
dup #259
