### ISSUE TITLE
mock requires new setuptools

### ISSUE THREAD

**Issue by russellballestrini** [testing-cabal/mock#284]
I tried installing mock==1.1.1, 1.1.2, 1.1.3 but got the same error:

```
Downloading/unpacking mock==1.1.1 (from botoform==0.0.1)
  Running setup.py egg_info for package mock
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/botoform/build/mock/setup.py", line 10, in <module>
        setuptools_installed = StrictVersion(setuptools.version.__version__)
    AttributeError: 'module' object has no attribute 'version'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/botoform/build/mock/setup.py", line 10, in <module>

    setuptools_installed = StrictVersion(setuptools.version.__version__)

AttributeError: 'module' object has no attribute 'version'
```

I fixed this error by upgrading setuptools:

```
pip install --upgrade setuptools
Downloading/unpacking distribute from https://pypi.python.org/packages/source/d/distribute/distribute-0.7.3.zip#md5=c6c59594a7b180af57af8a0cc0cf5b4a
  Downloading distribute-0.7.3.zip (145Kb): 145Kb downloaded
  Running setup.py egg_info for package distribute
    
Downloading/unpacking setuptools>=0.7 (from distribute)
  Downloading setuptools-18.0.1.tar.gz (630Kb): 630Kb downloaded
  Running setup.py egg_info for package setuptools
    
Installing collected packages: distribute, setuptools
  Found existing installation: distribute 0.6.24
    Uninstalling distribute:
      Successfully uninstalled distribute
  Running setup.py install for distribute
    
  Running setup.py install for setuptools
    
    Installing easy_install script to /botoform/bin
    Installing easy_install-2.7 script to /botoform/bin
Successfully installed distribute setuptools
Cleaning up...
```

**Comment by rbtcollins** [comment]
DUp of #279
