### ISSUE TITLE
ValueError: invalid version number '0.6c11' when pip installing mock-1.3.0

### ISSUE THREAD

**Issue by ryanschneider** [testing-cabal/mock#295]
As soon as mock-1.3.0 showed up on pypi I'm now getting this error installing mock as a downstream dependency for matplotlib:

```
Collecting mock (from matplotlib>=1.3.1->-r /path/to/virtualenv/project/pip-requirements.txt (line 6))
  Using cached mock-1.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-95QMUg/mock/setup.py", line 10, in <module>
        setuptools_installed = StrictVersion(setuptools.__version__)
      File "/usr/local/lib/python2.7/distutils/version.py", line 40, in __init__
        self.parse(vstring)
      File "/usr/local/lib/python2.7/distutils/version.py", line 107, in parse
        raise ValueError, "invalid version number '%s'" % vstring
    ValueError: invalid version number '0.6c11'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-95QMUg/mock
```

This is using pip 7.1.0:

```
/path/to/virtualenv/bin/pip -V
pip 7.1.0 from /path/to/virtualenv/lib/python2.7/site-packages (python 2.7)
```

**Comment by rbtcollins** [comment]
That looks like a setuptools version number, and suggests that we need to modify the version cross-check code. That said, setuptools 0.6c11 is too old to intall mock, so you'll need to upgrade to 17.1 or newer.

**Comment by ryanschneider** [comment]
Cool, thanks, upgrading to setuptools-18.0.1 allowed me to install mock-1.3.0.  FWIW, I was previously able to install mock-1.0.1 with 0.6c11, but I see that's ancient so understand you guys not wanting to support it. :)
