### ISSUE TITLE
1.3.0 is not importable: AttributeError: 'VersionInfo' object has no attribute 'semantic_version'

### ISSUE THREAD

**Issue by yarikoptic** [testing-cabal/mock#301]
Reported in debian originally
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=793945

```
(git)hopa:~/proj/misc/mock[master]git
$> PYTHONPATH=$PWD python -c 'import mock'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "mock/__init__.py", line 2, in <module>
    import mock.mock as _mock
  File "mock/mock.py", line 71, in <module>
    _v = VersionInfo('mock').semantic_version()
AttributeError: 'VersionInfo' object has no attribute 'semantic_version'

$> git describe                           
1.3.0  
```

**Comment by yarikoptic** [comment]
my bad -- missed the version depends on pbr and the one in debian sid is outdated a bit ;-)
