### ISSUE TITLE
Crash on comparing call_args with long strings

### ISSUE THREAD

**Issue by Wilfred** [testing-cabal/mock#308]
```
>>> from mock import Mock
>>> m = Mock()
>>> m(1, 2)
<Mock name='mock()' id='139781492681104'>
>>> m.call_args == "foob"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wilfred/.py_envs/trifle/lib/python2.7/site-packages/mock.py", line 2061, in __eq__
    first, second = other
ValueError: too many values to unpack
```

I'd have expected this to return `False` instead of raising an exception.

(Migrated from [this Google code issue](http://code.google.com/p/mock/issues/detail?id=232)).

**Comment by Wilfred** [comment]
Oh, this has been automatically imported: see #232.
