### ISSUE TITLE
AttributeError: Distribution instance has no attribute 'pbr'

### ISSUE THREAD

**Issue by mbrownGraham** [testing-cabal/mock#329]
Hello,
When installing/running mock using setuptools (python setup.py test) I get the following error: 

```py2.7.egg
running egg_info
writing appfeeds.egg-info/PKG-INFO
writing top-level names to appfeeds.egg-info/top_level.txt
writing dependency_links to appfeeds.egg-info/dependency_links.txt
writing entry points to appfeeds.egg-info/entry_points.txt
Traceback (most recent call last):
  File "setup.py", line 27, in <module>
    tests_require=['nose', 'mock==1.3.0']
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/newmaniese/VirtualEnvs/appfeeds/lib/python2.7/site-packages/setuptools/command/test.py", line 142, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/Users/newmaniese/VirtualEnvs/appfeeds/lib/python2.7/site-packages/setuptools/command/test.py", line 106, in with_project_on_sys_path
    self.run_command('egg_info')
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/newmaniese/VirtualEnvs/appfeeds/lib/python2.7/site-packages/setuptools/command/egg_info.py", line 173, in run
    writer(self, ep.name, os.path.join(self.egg_info, ep.name))
  File "/Users/newmaniese/Projects/appfeeds/.eggs/pbr-1.8.0-py2.7.egg/pbr/pbr_json.py", line 23, in write_pbr_json
    if not cmd.distribution.pbr:
AttributeError: Distribution instance has no attribute 'pbr'' 


in my setup.py file -> tests_require=['nose', 'mock==1.3.0']

**Comment by rbtcollins** [comment]
This is https://bugs.launchpad.net/pbr/+bug/1493735 - its being worked on there.
