### ISSUE TITLE
"TypeError: too many positional arguments" when decorated vararg function is patched with autospec

### ISSUE THREAD

**Issue by vitaly-krugl** [testing-cabal/mock#338]
The following code snippet works fine with mock v 1.0.1, but fails with mock 1.1.0, 1.2.0, and the latest 1.3.0 and Python 2.6/2.7. It also works fine with mock v1.3.0 and Python 3.3, 3.4, and 3.5.

The failing test run below is on Mac OS X Yosemite with python 2.7.10; the same failure is reproducible in Linux Travis builds in the https://github.com/pika/pika project with both Python 2.6 and 2.7.

```
import functools
import mock


def my_decorator(function):

  @functools.wraps(function)
  def wrapper(*args, **kwargs):
    """Dummy decorator for reproducing the bug

    """
    return function(*args, **kwargs)

  return wrapper


class MyClass(object):

  @my_decorator
  def process(self, prefix, *args, **kwargs):
    print("please help me solve this mock problem")


def main():
  print("mock version:", mock.__version__)

  my = MyClass()

  with mock.patch.object(my, "process", autospec=True):
    my.process("abc", 9)


if __name__ == "__main__":
  main()
```

The failure looks like this:

```
$ python ~/mock_fail.py 
mock version: 1.3.0
Traceback (most recent call last):
  File "/Users/vkruglikov/mock_fail.py", line 42, in <module>
    main()
  File "/Users/vkruglikov/mock_fail.py", line 37, in main
    my.process("abc", 9)
  File "<string>", line 2, in process
  File "/Users/vkruglikov/Library/Python/2.7/lib/python/site-packages/mock/mock.py", line 310, in checksig
    sig.bind(*args, **kwargs)
  File "/Users/vkruglikov/Library/Python/2.7/lib/python/site-packages/mock/mock.py", line 95, in fixedbind
    return self._bind(args, kwargs)
  File "/Users/vkruglikov/Library/Python/2.7/lib/python/site-packages/funcsigs/__init__.py", line 717, in _bind
    raise TypeError('too many positional arguments')
TypeError: too many positional arguments```

**Comment by asottile** [comment]
Here's a simpler example without varargs:

```python
import functools
import mock


def dec(func):
    """trivial decorator"""
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        return func(*args, **kwargs)
    return wrapper


class C(object):
    @dec
    def f(self, a, b, c):
        print(a, b, c)


C2 = mock.create_autospec(C)
C2.f(1, 2, 3)
```

**Comment by rbtcollins** [comment]
I think this too is due to testing-cabal/funcsigs#13

**Comment by rbtcollins** [comment]
Thanks @mfield for that demonstrative test.

**Comment by mfield** [comment]
:+1: excited for the fix
