### ISSUE TITLE
Regression: Double patching instance method: AttributeError: Mock object has no attribute '__name__'

### ISSUE THREAD

**Issue by asottile** [testing-cabal/mock#350]
## Example
```python
import mock

class C(object):
    def f(self):
        pass

c = C()

with mock.patch.object(c, 'f', autospec=True):
    with mock.patch.object(c, 'f', autospec=True):
        pass
```

## mock 1.3 / 2.0

```python
# python test.py
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    with mock.patch.object(c, 'f', autospec=True):
  File "/nail/home/asottile/pg/yelp-main/virtualenv_run/lib/python2.7/site-packages/mock/mock.py", line 1450, in __enter__
    _name=self.attribute, **kwargs)
  File "/nail/home/asottile/pg/yelp-main/virtualenv_run/lib/python2.7/site-packages/mock/mock.py", line 2370, in create_autospec
    _check_signature(original, new, skipfirst=skipfirst)
  File "/nail/home/asottile/pg/yelp-main/virtualenv_run/lib/python2.7/site-packages/mock/mock.py", line 210, in _check_signature
    _copy_func_details(func, checksig)
  File "/nail/home/asottile/pg/yelp-main/virtualenv_run/lib/python2.7/site-packages/mock/mock.py", line 215, in _copy_func_details
    funcopy.__name__ = func.__name__
  File "/nail/home/asottile/pg/yelp-main/virtualenv_run/lib/python2.7/site-packages/mock/mock.py", line 698, in __getattr__
    raise AttributeError("Mock object has no attribute %r" % name)
AttributeError: Mock object has no attribute '__name__'
```

## mock 1.0.1
```
# python test.py
#
```

**Comment by asottile** [comment]
This appears to be a problem with cpython itself:

## diff
```diff
-import mock
+from unittest import mock
```

## py33
```python
# python3.3 test.py
#
```

## py34
```python
# python3.4 test.py
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    with mock.patch.object(c, 'f', autospec=True):
  File "/usr/lib/python3.4/unittest/mock.py", line 1278, in __enter__
    _name=self.attribute, **kwargs)
  File "/usr/lib/python3.4/unittest/mock.py", line 2165, in create_autospec
    _check_signature(original, new, skipfirst=skipfirst)
  File "/usr/lib/python3.4/unittest/mock.py", line 108, in _check_signature
    _copy_func_details(func, checksig)
  File "/usr/lib/python3.4/unittest/mock.py", line 113, in _copy_func_details
    funcopy.__name__ = func.__name__
  File "/usr/lib/python3.4/unittest/mock.py", line 568, in __getattr__
    raise AttributeError("Mock object has no attribute %r" % name)
AttributeError: Mock object has no attribute '__name__'
```

**Comment by asottile** [comment]
Created cpython bug here: http://bugs.python.org/issue26704

**Comment by rbtcollins** [comment]
Thanks.

**Comment by asottile** [comment]
@rbtcollins I wrote a patch and a test here: https://bugs.python.org/file42384/patch

I noticed the stdlib doesn't seem to have any tests for mock, am I looking in the wrong place (I want to make sure I didn't break anything else :D)

**Comment by rbtcollins** [comment]
Lib/unittest/test/testmock/ has the tests. yeah, its a little awkward :).

**Comment by asottile** [comment]
awkward!

I improved my patch based on that (and the failing tests the original patch caused): http://bugs.python.org/file42387/patch2
