### ISSUE TITLE
Ubilinux Install Problem

### ISSUE THREAD

**Issue by jmwright** [testing-cabal/mock#401]
I'm running Ubilinux (Debian) 150309 on an Intel Edison using pip installed via apt-get. Here's my pip version info:

```
$ pip --version
pip 1.1 from /usr/lib/python2.7/dist-packages (python 2.7)
```

I get the following error when I try to install mock.

```
$ sudo pip install mock
sudo: unable to resolve host ubilinux
Downloading/unpacking mock
  Running setup.py egg_info for package mock
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "/home/edison/kalliope/build/mock/pbr-2.0.0-py2.7.egg/pbr/core.py", line 111, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "/home/edison/kalliope/build/mock/pbr-2.0.0-py2.7.egg/pbr/util.py", line 251, in cfg_to_args
        kwargs = setup_cfg_to_setup_kwargs(config, script_args)
      File "/home/edison/kalliope/build/mock/pbr-2.0.0-py2.7.egg/pbr/util.py", line 434, in setup_cfg_to_setup_kwargs
        if pkg_resources.evaluate_marker('(%s)' % env_marker):
    AttributeError: 'module' object has no attribute 'evaluate_marker'
    error in setup command: Error parsing /home/edison/kalliope/build/mock/setup.cfg: AttributeError: 'module' object has no attribute 'evaluate_marker'
    Complete output from command python setup.py egg_info:
    ERROR:root:Error parsing

Traceback (most recent call last):

  File "/home/edison/kalliope/build/mock/pbr-2.0.0-py2.7.egg/pbr/core.py", line 111, in pbr

    attrs = util.cfg_to_args(path, dist.script_args)

  File "/home/edison/kalliope/build/mock/pbr-2.0.0-py2.7.egg/pbr/util.py", line 251, in cfg_to_args

    kwargs = setup_cfg_to_setup_kwargs(config, script_args)

  File "/home/edison/kalliope/build/mock/pbr-2.0.0-py2.7.egg/pbr/util.py", line 434, in setup_cfg_to_setup_kwargs

    if pkg_resources.evaluate_marker('(%s)' % env_marker):

AttributeError: 'module' object has no attribute 'evaluate_marker'

error in setup command: Error parsing /home/edison/kalliope/build/mock/setup.cfg: AttributeError: 'module' object has no attribute 'evaluate_marker'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /home/edison/kalliope/build/mock
Storing complete log in /root/.pip/pip.log
```

**Comment by rbtcollins** [comment]
Upgrade your pip and setuptools - they are many years old.
