### ISSUE TITLE
fix pypi test failure.

### ISSUE THREAD

**Issue by cjw296** [testing-cabal/mock#438]
I'm going to stop the pypi job from failing the Travis CI build.
Opening this bug to fix the failure and then revert the change to allow pypi failures.

**Comment by tirkarthi** [comment]
Interesting :) here is a simple reproducer of the pypy error.

```python
try:
    from mock import *
except ImportError:
    from unittest.mock import *

mock = create_autospec(dict)
mock.pop(3)
mock.pop.assert_called_with(3)
```

Python 2.7.14 - passes
CPython master - passes
pypy 5.8.0 - fails

```python
Traceback (most recent call last):
  File "foo.py", line 7, in <module>
    mock.pop(3)
  File "/tmp/pypy-env/site-packages/mock/mock.py", line 1064, in __call__
    _mock_self._mock_check_sig(*args, **kwargs)
  File "/tmp/pypy-env/site-packages/mock/mock.py", line 212, in checksig
    sig.bind(*args, **kwargs)
  File "/tmp/pypy-env/site-packages/funcsigs/__init__.py", line 792, in bind
    return args[0]._bind(args[1:], kwargs)
  File "/tmp/pypy-env/site-packages/funcsigs/__init__.py", line 717, in _bind
    raise TypeError(msg)
TypeError: 'default' parameter lacking default value
```

I tried adding adding print statements in the mock library inside `_get_signature_object` where the signature is returned. For pypy it actually tries to copy the whole dict object properties thus trying to set the signature. Trying to print `func`, `sig_func` and `inspectgetsignature(sig_func)`. The output on pypy is as below. I have snipped since it's very lengthy but it tries to set the signature of all the methods of a dict and also twice?

```
(<bound method type.__call__ of <type 'dict'>>, <_functools.partial object at 0x000000010f2277f8>)
(*args, **keywords)
(<bound method type.__call__ of <type 'dict'>>, <_functools.partial object at 0x000000010f227830>)
(*args, **keywords)
(<unbound method dict.clear>, <_functools.partial object at 0x000000010f227868>)
()
(<unbound method dict.clear>, <_functools.partial object at 0x000000010f536f00>)
()
(<unbound method dict.copy>, <_functools.partial object at 0x000000010f536f38>)
()
(<unbound method dict.copy>, <_functools.partial object at 0x000000010f536f70>)
()
(<bound method type.fromkeys of <type 'dict'>>, <bound method type.fromkeys of <type 'dict'>>)
(keys, fill)
(<bound method type.fromkeys of <type 'dict'>>, <bound method type.fromkeys of <type 'dict'>>)
(keys, fill)
[snip]
(<unbound method dict.keys>, <_functools.partial object at 0x000000010f5c0c60>)
()
(<unbound method dict.keys>, <_functools.partial object at 0x000000010f5c0c98>)
()
(<unbound method dict.pop>, <_functools.partial object at 0x000000010f5c0cd0>)
(key, default)
(<unbound method dict.pop>, <_functools.partial object at 0x000000010f5d99f0>)
(key, default)
[snip]
(<unbound method dict.viewvalues>, <_functools.partial object at 0x000000010f600528>)
()
(<unbound method dict.viewvalues>, <_functools.partial object at 0x000000010f600560>)
()
```

This specific line sets the signature for `pop` as `(key, default)`

```
(<unbound method dict.pop>, <_functools.partial object at 0x000000010f5c0cd0>)
(key, default)
```

Meanwhile on python 2.7.14 this block produces `ValueError` returning no signature. On CPython master it gives below : 

```
functools.partial(<slot wrapper '__init__' of 'dict' objects>, None) <slot wrapper '__init__' of 'dict' objects>
(*args, **kwargs)
functools.partial(<slot wrapper '__init__' of 'dict' objects>, None) <slot wrapper '__init__' of 'dict' objects>
(*args, **kwargs)
functools.partial(<method-wrapper '__call__' of type object at 0x10bb601c0>, None) <method-wrapper '__call__' of type object at 0x10bb601c0>
(*args, **kwargs)
functools.partial(<method-wrapper '__call__' of type object at 0x10bb601c0>, None) <method-wrapper '__call__' of type object at 0x10bb601c0>
(*args, **kwargs)
functools.partial(<method-wrapper '__call__' of method_descriptor object at 0x10bd4ca60>, None) <method-wrapper '__call__' of method_descriptor object at 0x10bd4ca60>
(*args, **kwargs)
<method-wrapper '__call__' of method_descriptor object at 0x10bd4ca60> <method-wrapper '__call__' of method_descriptor object at 0x10bd4ca60>
(*args, **kwargs)
```

So pypy does something along copying all methods of `dict` with it's original signature. I tried getting to the point where pypy last passes but the logs on Travis were are all `null` with Travis passed. So I don't know how it broke. I will try some more debugging once I get some more time.

**Comment by cjw296** [comment]
Fantastic, thanks for digging in to this!

**Comment by tirkarthi** [comment]
I can see some differences in how `getattr(dict, 'pop')` behaves on pypy and python 2. On pypy it returns the attribute as unbound method and on python 2 it's a bound method. So this causes a behavior difference on `not isinstance(original, FunctionTypes)` statement where PyPy returns False and Python 2 returns True.

PyPy

```python
(pypy-env) ➜  /tmp python
Python 2.7.13 (c925e73810367cd960a32592dd7f728f436c125c, Jun 09 2017, 00:47:59)
[PyPy 5.8.0 with GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>> getattr(dict, 'pop')
<unbound method dict.pop>
```

python 2

```python
(py2-venv) ➜  /tmp python2
Python 2.7.14 (default, Mar 12 2018, 13:54:56)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> getattr(dict, 'pop')
<method 'pop' of 'dict' objects>
```

When a spec is given for `create_autospec` then `dir(spec)` is executed to attach mocks to all the attributes. Printing `(original, not isinstance(original, FunctionTypes))` inside `for entry in dir(spec)` loop gives different output thus causing different branches to be taken.

PyPy

```python
(<unbound method dict.clear>, False)
(<unbound method dict.copy>, False)
(<bound method type.fromkeys of <type 'dict'>>, False)
(<unbound method dict.get>, False)
[snip]
```

Python 2

```python
(<method 'clear' of 'dict' objects>, True)
(<method 'copy' of 'dict' objects>, True)
(<built-in method fromkeys of type object at 0x10dbb1cd0>, True)
(<method 'get' of 'dict' objects>, True)
(<method 'has_key' of 'dict' objects>, True)
[snip]
```

PyPy has some notes on this but my knowledge of internals of CPython is very low so I might be misquoting from http://doc.pypy.org/en/latest/cpython_differences.html

```
on CPython, [].__add__ is a method-wrapper, and list.__add__ is a slot wrapper. 
On PyPy these are normal bound or unbound method objects. This can 
occasionally confuse some tools that inspect built-in types. For example, 
the standard library inspect module has a function ismethod() that returns True 
on unbound method objects but False on method-wrappers or slot wrappers. 
On PyPy we can’t tell the difference, so ismethod([].__add__) == ismethod(list.__add__) == True.
```

```
(pypy-env) ➜  /tmp pypy
Python 2.7.13 (c925e73810367cd960a32592dd7f728f436c125c, Jun 09 2017, 00:47:59)
[PyPy 5.8.0 with GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>> {}.pop
<bound method dict.pop of {}>
>>>> dict.pop
<unbound method dict.pop>
```


```
(py2-venv) ➜  /tmp python2
Python 2.7.14 (default, Mar 12 2018, 13:54:56)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> {}.pop
<built-in method pop of dict object at 0x10126c5c8>
>>> dict.pop
<method 'pop' of 'dict' objects>
```

I don't know how pypy2 used to pass (maybe this test was not present before?) and how pypy3 works since I don't have a pypy3 build with me now.

**Comment by tirkarthi** [comment]
I hope I finally got to it. funcsigs produces different signatures for `dict.pop` on different versions of pypy so I guess it's not the unbound vs bound case I posted earlier. pypy hasn't changed the signature which would be incorrect but it's more like something else caused different signatures to be produced by funcsigs. I downloaded different versions of pypy and tried installing mock to run the reproducer using `dict.pop` and results as below. I haven't checked this for other method signatures of dict. Current Travis builds use pypy 5.8.0 where the tests fail and I guess the previous ones where the tests passed should have used 5.6.0 and below.

Maybe this should be fixed in funcsigs which I believe is at https://github.com/testing-cabal/funcsigs/ as per the PyPI code. But the last commit was 2.5 years ago with last CI check using very old version of pypy so I am not sure of the maintenance :( funcsigs is needed for Python 2.7 support I suppose for retrieving signature.

pypy3 6.0.0 (self, key, default=\<no value\>) - Test passes

```
./bin/pypy3
Python 3.5.3 (fdd60ed87e94, Apr 24 2018, 06:10:04)
[PyPy 6.0.0 with GCC 6.2.0 20160901] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>> import inspect
>>>> inspect.signature(dict.pop)
<Signature (self, key, default=<no value>)>
```

pypy 5.6.0 (self, key, *defaults) - Test passes

```
 pypy
Python 2.7.12 (aff251e543859ce4508159dd9f1a82a2f553de00, Nov 12 2016, 08:50:18)
[PyPy 5.6.0 with GCC 6.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>> import funcsigs
>>>> print(funcsigs.signature(dict.pop))
(self, key, *defaults)
```

pypy 5.7.0 (self, key, default) - Test fails

```
pypy
Python 2.7.13 (fa3249d55d15b9829e1be69cdf45b5a44cec902d, Mar 21 2017, 14:51:03)
[PyPy 5.7.0 with GCC 6.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>> import funcsigs
>>>> print(funcsigs.signature(dict.pop))
(self, key, default)
```

pypy 6.0.0 (self, key, default) - Test fails

```
pypy
Python 2.7.13 (6.0.0+dfsg-1~ppa1~ubuntu16.04, Apr 28 2018, 03:15:13)
[PyPy 6.0.0 with GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>> import funcsigs
>>>> print(funcsigs.signature(dict.pop))
(self, key, default)
```

**Comment by cjw296** [comment]
The tough one: How much do we care about pypy (which I presume is "Python 2")? 
I guess that question become: when does funcsigs arrive in Python 3? If it's 3.6 above, I'm tempted to suggest a PR (if you fancy working one up?) that just marks this as an expected failure on pypy, until someone who uses pypy actually turns up and complains about it...

...of course, if you fancied picking up maintenance of the funcsigs backport, that'll likely make even more people happy for the next year for few! (I know I'll probably need it for [mush](https://mush.readthedocs.io) or [testfixtures](https://testfixtures.readthedocs.io) at some point!).

**Comment by tirkarthi** [comment]
> I'm tempted to suggest a PR (if you fancy working one up?) that just marks this as an expected failure on pypy, until someone who uses pypy actually turns up and complains about it...

I guess this is a good idea for now to skip the particular test on pypy2 to make sure there are no regressions on other tests at least. I will make a PR shortly to skip the test and to make pypy2 mandatory again travis.

> ...of course, if you fancied picking up maintenance of the funcsigs backport, that'll likely make even more people happy for the next year for few! (I know I'll probably need it for mush or testfixtures at some point!).

Unfortunately, I am not sure I have the bandwidth for funcsigs. Out of curiosity I just triggered a build for funcsigs since there is no activity for two years. The builds fail on python 2.6 and 3.3 since latest pip dropped support for older versions with other versions passing https://travis-ci.org/tirkarthi/funcsigs/jobs/471625354

**Comment by pquentin** [comment]
For what it's worth, this also breaks the PyPy urllib3 test suite for Python 2. In https://travis-ci.org/urllib3/urllib3/jobs/572772982, search for "TypeError: 'cadata' parameter lacking default value". We're also going to skip the broken tests on PyPy
